### ISSUE TITLE
Native extension build error when `bundle install` master version

### ISSUE THREAD

**Issue by ybiquitous** [ruby/bigdecimal#197]
## Summary

I find the following build error when running `bundle install` for the GitHub `master` version (bdf2364).

```
extconf.rb:9:in `check_bigdecimal_version': undefined method `[]' for nil:NilClass (NoMethodError)
	from extconf.rb:43:in `<main>'
```

It seems `gemspec_path` does not include `bigdecimal_version`:

https://github.com/ruby/bigdecimal/blob/bdf2364a364db6c46b86bf00c4aab715b50d8fb8/ext/bigdecimal/extconf.rb#L7-L9

## Reproduction

```console
$ docker run -it --rm ruby:3.0.2 bash
root@30ce135f0470:/# ruby -v
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [aarch64-linux]

root@30ce135f0470:/# bundle -v
Bundler version 2.2.22

root@30ce135f0470:/# mkdir /tmp/work && \
  cd /tmp/work && \
  echo 'source "https://rubygems.org"' >> Gemfile && \
  echo 'gem "bigdecimal", github: "ruby/bigdecimal", ref: "bdf2364"' >> Gemfile

root@30ce135f0470:/tmp/work# cat Gemfile
source "https://rubygems.org"
gem "bigdecimal", github: "ruby/bigdecimal", ref: "bdf2364"

root@30ce135f0470:/tmp/work# bundle install
Fetching https://github.com/ruby/bigdecimal.git
Resolving dependencies...
Using bigdecimal 3.1.0.dev from https://github.com/ruby/bigdecimal.git (at bdf2364@bdf2364)
Using bundler 2.2.22
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/bundler/gems/bigdecimal-bdf2364a364d/ext/bigdecimal
/usr/local/bin/ruby -I /usr/local/lib/ruby/3.0.0 -r ./siteconf20211027-9-g5fug6.rb extconf.rb
checking RUBY_BIGDECIMAL_VERSION... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
extconf.rb:9:in `check_bigdecimal_version': undefined method `[]' for nil:NilClass (NoMethodError)
	from extconf.rb:43:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /usr/local/bundle/bundler/gems/bigdecimal-bdf2364a364d for inspection.
Results logged to /usr/local/bundle/bundler/gems/extensions/aarch64-linux/3.0.0/bigdecimal-bdf2364a364d/gem_make.out

An error occurred while installing bigdecimal (3.1.0.dev), and Bundler cannot continue.

In Gemfile:
  bigdecimal
```

## Environment

- Ruby: `ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [aarch64-linux]`
- Bundler: `Bundler version 2.2.22`
- BigDecimal: bdf2364

**Comment by mrkn** [comment]
The master version is not for usual use.  Why do you need the master version?

**Comment by ybiquitous** [comment]
Ah, thank you for the advice. I'd just like to use the new RDoc for `BigDecimal()`. 😃 

### `master`

https://github.com/ruby/bigdecimal/blob/bdf2364a364db6c46b86bf00c4aab715b50d8fb8/ext/bigdecimal/bigdecimal.c#L3081-L3083

### `v3.0.2`

https://github.com/ruby/bigdecimal/blob/186a74f4449dd17b4595d44e092a98206a411a28/ext/bigdecimal/bigdecimal.c#L2836-L2837

**Comment by mrkn** [comment]
The next version will be released before 25 Dec.  Please wait for the next version.

Thanks.
