### ISSUE TITLE
Use RUBY_TYPED_EMBEDDABLE in BigDecimal

### ISSUE THREAD

**Issue by mrkn** [ruby/bigdecimal#293]
Ruby 3.3 introduces `RUBY_TYPED_EMBEDDABLE`.  Now a BigDecimal with a small amount of digits can embed its internal data.

**Comment by barnett617** [comment]
I also have ruby version problem. I'm using Ruby 3.4.2, when I build lynx explorer for iOS as follows

```sh
SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk bundle install
./bundle_install.sh
```

It comes 

```sh
Bundle complete! 2 Gemfile dependencies, 41 gems now installed.
Bundled gems are installed into `/Users/xxx/GitHub/lynx-root/src/lynx`
```

with

```sh
bundler: failed to load command: pod (/Users/xxx/GitHub/lynx-root/src/lynx/ruby/3.4.0/bin/pod)
<internal:/opt/homebrew/Cellar/ruby/3.4.2/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:37:in 'Kernel#require': cannot load such file -- bigdecimal (LoadError)
        from <internal:/opt/homebrew/Cellar/ruby/3.4.2/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:37:in 'Kernel#require'
        from /Users/xxx/GitHub/lynx-root/src/lynx/ruby/3.4.0/gems/activesupport-6.1.7.10/lib/active_support/xml_mini.rb:5:in '<top (required)>'
        from <internal:/opt/homebrew/Cellar/ruby/3.4.2/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:37:in 'Kernel#require'
        from <internal:/opt/homebrew/Cellar/ruby/3.4.2/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:37:in 'Kernel#require'
        from /Users/xxx/GitHub/lynx-root/src/lynx/ruby/3.4.0/gems/activesupport-6.1.7.10/lib/active_support/core_ext/array/conversions.rb:3:in '<top (required)>'
        from <internal:/opt/homebrew/Cellar/ruby/3.4.2/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:37:in 'Kernel#require'
        from <internal:/opt/homebrew/Cellar/ruby/3.4.2/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:37:in 'Kernel#require'
        from /Users/xxx/GitHub/lynx-root/src/lynx/ruby/3.4.0/gems/cocoapods-1.11.3/lib/cocoapods.rb:9:in '<top (required)>'
        from <internal:/opt/homebrew/Cellar/ruby/3.4.2/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:37:in 'Kernel#require'
        from <internal:/opt/homebrew/Cellar/ruby/3.4.2/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:37:in 'Kernel#require'
        from /Users/xxx/GitHub/lynx-root/src/lynx/ruby/3.4.0/gems/cocoapods-1.11.3/bin/pod:36:in '<top (required)>'
        from /Users/xxx/GitHub/lynx-root/src/lynx/ruby/3.4.0/bin/pod:25:in 'Kernel#load'
        from /Users/xxx/GitHub/lynx-root/src/lynx/ruby/3.4.0/bin/pod:25:in '<top (required)>'
        from /opt/homebrew/lib/ruby/gems/3.4.0/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:58:in 'Kernel.load'
        from /opt/homebrew/lib/ruby/gems/3.4.0/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:58:in 'Bundler::CLI::Exec#kernel_load'
        from /opt/homebrew/lib/ruby/gems/3.4.0/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:23:in 'Bundler::CLI::Exec#run'
        from /opt/homebrew/lib/ruby/gems/3.4.0/gems/bundler-2.4.20/lib/bundler/cli.rb:492:in 'Bundler::CLI#exec'
        from /opt/homebrew/lib/ruby/gems/3.4.0/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/command.rb:27:in 'Bundler::Thor::Command#run'
        from /opt/homebrew/lib/ruby/gems/3.4.0/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'Bundler::Thor::Invocation#invoke_command'
        from /opt/homebrew/lib/ruby/gems/3.4.0/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor.rb:392:in 'Bundler::Thor.dispatch'
        from /opt/homebrew/lib/ruby/gems/3.4.0/gems/bundler-2.4.20/lib/bundler/cli.rb:34:in 'Bundler::CLI.dispatch'
        from /opt/homebrew/lib/ruby/gems/3.4.0/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/base.rb:485:in 'Bundler::Thor::Base::ClassMethods#start'
        from /opt/homebrew/lib/ruby/gems/3.4.0/gems/bundler-2.4.20/lib/bundler/cli.rb:28:in 'Bundler::CLI.start'
        from /opt/homebrew/lib/ruby/gems/3.4.0/gems/bundler-2.4.20/exe/bundle:37:in 'block in <top (required)>'
        from /opt/homebrew/lib/ruby/gems/3.4.0/gems/bundler-2.4.20/lib/bundler/friendly_errors.rb:117:in 'Bundler.with_friendly_errors'
        from /opt/homebrew/lib/ruby/gems/3.4.0/gems/bundler-2.4.20/exe/bundle:29:in '<top (required)>'
        from /opt/homebrew/opt/ruby/bin/bundle:25:in 'Kernel#load'
        from /opt/homebrew/opt/ruby/bin/bundle:25:in '<main>'
```

I'm guessing whether it's related to the ruby issue https://github.com/ruby/bigdecimal/issues/289
